variables:
  MY_PROJECT_ID: "48321671"
  GIT_SYNC_URL: "https://$GITHUB_USERNAME_ROBOT:$GITHUB_TOKEN_ROBOT@github.com/NoFussComputing/nodered_ldap_self_service.git"
  

  PAGES_ENVIRONMENT_PATH: projects/ldap_self_service/

include:
  - project: nofusscomputing/projects/gitlab-ci
    ref: development
    file:
      - template/automagic.gitlab-ci.yaml


Github (Push --mirror):
  extends:
    - .git_push_mirror
  needs: []
  rules:
    - if: $GIT_SYNC_URL == null
      when: never
    - if: # Always sync including working branches
        $CI_PIPELINE_SOURCE == "push"
      when: always
    - when: never
