INHERIT: website-template/mkdocs.yml

docs_dir: 'docs'

repo_name: LDAP Self Service
repo_url: https://gitlab.com/nofusscomputing/projects/nodered_ldap_self_service
edit_uri: '/-/ide/project/nofusscomputing/projects/nodered_ldap_self_service/edit/development/-/docs/'

nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - projects/ldap_self_service/index.md

- Operations: 

  - operations/index.md

- Contact Us: contact.md

